/// Flutter icons DSIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DSIcons
///      fonts:
///       - asset: fonts/DSIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

// ignore_for_file: constant_identifier_names
class NuDSIcons {
  NuDSIcons._();

  static const _kFontFam = 'NuDSIcons';
  // static const String _kFontPkg = '';

  static const IconData add_circle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: null);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: null);
  static const IconData attach_file = IconData(0xe802, fontFamily: _kFontFam, fontPackage: null);
  static const IconData notification = IconData(0xe803, fontFamily: _kFontFam, fontPackage: null);
  static const IconData block = IconData(0xe804, fontFamily: _kFontFam, fontPackage: null);
  static const IconData today = IconData(0xe805, fontFamily: _kFontFam, fontPackage: null);
  static const IconData calendar_today = IconData(0xe806, fontFamily: _kFontFam, fontPackage: null);
  static const IconData camera_alt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: null);
  static const IconData chat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: null);
  static const IconData circle_check = IconData(0xe809, fontFamily: _kFontFam, fontPackage: null);
  static const IconData check = IconData(0xe80A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData clock = IconData(0xe80B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData circle_block = IconData(0xe80C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData contacts = IconData(0xe80D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData content_copy = IconData(0xe80E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData message = IconData(0xe80F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData file = IconData(0xe810, fontFamily: _kFontFam, fontPackage: null);
  static const IconData download = IconData(0xe811, fontFamily: _kFontFam, fontPackage: null);
  static const IconData email = IconData(0xe812, fontFamily: _kFontFam, fontPackage: null);
  static const IconData erase = IconData(0xe813, fontFamily: _kFontFam, fontPackage: null);
  static const IconData fingerprint = IconData(0xe814, fontFamily: _kFontFam, fontPackage: null);
  static const IconData headphones = IconData(0xe815, fontFamily: _kFontFam, fontPackage: null);
  static const IconData favorite = IconData(0xe816, fontFamily: _kFontFam, fontPackage: null);
  static const IconData mute = IconData(0xe817, fontFamily: _kFontFam, fontPackage: null);
  static const IconData hourglass_empty = IconData(0xe818, fontFamily: _kFontFam, fontPackage: null);
  static const IconData image_add = IconData(0xe819, fontFamily: _kFontFam, fontPackage: null);
  static const IconData image = IconData(0xe81A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData divider_sign = IconData(0xe81B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData link = IconData(0xe81C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData list = IconData(0xe81D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData location = IconData(0xe81E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData video_off = IconData(0xe81F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData unlock = IconData(0xe820, fontFamily: _kFontFam, fontPackage: null);
  static const IconData lock = IconData(0xe821, fontFamily: _kFontFam, fontPackage: null);
  static const IconData edit = IconData(0xe822, fontFamily: _kFontFam, fontPackage: null);
  static const IconData circle_play = IconData(0xe823, fontFamily: _kFontFam, fontPackage: null);
  static const IconData dashboard = IconData(0xe824, fontFamily: _kFontFam, fontPackage: null);
  static const IconData refresh = IconData(0xe825, fontFamily: _kFontFam, fontPackage: null);
  static const IconData circle_remove = IconData(0xe826, fontFamily: _kFontFam, fontPackage: null);
  static const IconData minus_sign = IconData(0xe827, fontFamily: _kFontFam, fontPackage: null);
  static const IconData sync = IconData(0xe828, fontFamily: _kFontFam, fontPackage: null);
  static const IconData send = IconData(0xe829, fontFamily: _kFontFam, fontPackage: null);
  static const IconData face_sad = IconData(0xe82A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData face_neutral = IconData(0xe82B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData face_happy = IconData(0xe82C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData face_sadness = IconData(0xe82D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData face_happiness = IconData(0xe82E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData config = IconData(0xe82F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData share = IconData(0xe830, fontFamily: _kFontFam, fontPackage: null);
  static const IconData upload = IconData(0xe831, fontFamily: _kFontFam, fontPackage: null);
  static const IconData shield = IconData(0xe832, fontFamily: _kFontFam, fontPackage: null);
  static const IconData smartphone_lock = IconData(0xe833, fontFamily: _kFontFam, fontPackage: null);
  static const IconData smartphone = IconData(0xe834, fontFamily: _kFontFam, fontPackage: null);
  static const IconData filter_list = IconData(0xe835, fontFamily: _kFontFam, fontPackage: null);
  static const IconData quarter_circle = IconData(0xe836, fontFamily: _kFontFam, fontPackage: null);
  static const IconData star = IconData(0xe837, fontFamily: _kFontFam, fontPackage: null);
  static const IconData tag_add = IconData(0xe838, fontFamily: _kFontFam, fontPackage: null);
  static const IconData delete = IconData(0xe839, fontFamily: _kFontFam, fontPackage: null);
  static const IconData tune = IconData(0xe83A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData undo = IconData(0xe83B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData person_add = IconData(0xe83C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData person_profile = IconData(0xe83D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData person = IconData(0xe83E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData visibility_off = IconData(0xe83F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData visibility = IconData(0xe840, fontFamily: _kFontFam, fontPackage: null);
  static const IconData error = IconData(0xe841, fontFamily: _kFontFam, fontPackage: null);
  static const IconData warning = IconData(0xe842, fontFamily: _kFontFam, fontPackage: null);
  static const IconData airplane = IconData(0xe843, fontFamily: _kFontFam, fontPackage: null);
  static const IconData phone_down = IconData(0xe844, fontFamily: _kFontFam, fontPackage: null);
  static const IconData gamepad = IconData(0xe845, fontFamily: _kFontFam, fontPackage: null);
  static const IconData pingpong = IconData(0xe846, fontFamily: _kFontFam, fontPackage: null);
  static const IconData shopping_cart = IconData(0xe847, fontFamily: _kFontFam, fontPackage: null);
  static const IconData hospital = IconData(0xe848, fontFamily: _kFontFam, fontPackage: null);
  static const IconData home = IconData(0xe849, fontFamily: _kFontFam, fontPackage: null);
  static const IconData grid_view = IconData(0xe84A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData restaurant = IconData(0xe84B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData tool = IconData(0xe84C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData heart = IconData(0xe84D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData car = IconData(0xe84E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData previous_step = IconData(0xe84F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData bank = IconData(0xe850, fontFamily: _kFontFam, fontPackage: null);
  static const IconData bar_code = IconData(0xe851, fontFamily: _kFontFam, fontPackage: null);
  static const IconData microphone = IconData(0xe852, fontFamily: _kFontFam, fontPackage: null);
  static const IconData import_export = IconData(0xe853, fontFamily: _kFontFam, fontPackage: null);
  static const IconData percert_sign = IconData(0xe854, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_down = IconData(0xe855, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_up = IconData(0xe856, fontFamily: _kFontFam, fontPackage: null);
  static const IconData payments = IconData(0xe857, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money = IconData(0xe858, fontFamily: _kFontFam, fontPackage: null);
  static const IconData umbruella = IconData(0xe85A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_pig_improve = IconData(0xe85B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_pig_remove = IconData(0xe85C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_pig_add = IconData(0xe85D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_pig = IconData(0xe85E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData machine_card = IconData(0xe85F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData receipt = IconData(0xe860, fontFamily: _kFontFam, fontPackage: null);
  static const IconData chat_money = IconData(0xe861, fontFamily: _kFontFam, fontPackage: null);
  static const IconData gift = IconData(0xe862, fontFamily: _kFontFam, fontPackage: null);
  static const IconData store = IconData(0xe863, fontFamily: _kFontFam, fontPackage: null);
  static const IconData signal = IconData(0xe865, fontFamily: _kFontFam, fontPackage: null);
  static const IconData chevron_left = IconData(0xe866, fontFamily: _kFontFam, fontPackage: null);
  static const IconData arrow_down = IconData(0xe867, fontFamily: _kFontFam, fontPackage: null);
  static const IconData arrow_left = IconData(0xe868, fontFamily: _kFontFam, fontPackage: null);
  static const IconData arrow_right = IconData(0xe869, fontFamily: _kFontFam, fontPackage: null);
  static const IconData arrow_diagonal = IconData(0xe86A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData arrow_up = IconData(0xe86B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData chevron_right = IconData(0xe86C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData close = IconData(0xe86D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData equal_sign = IconData(0xe86E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData expand_less = IconData(0xe86F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData expand_more = IconData(0xe870, fontFamily: _kFontFam, fontPackage: null);
  static const IconData more_horizontal = IconData(0xe871, fontFamily: _kFontFam, fontPackage: null);
  static const IconData more_vertical = IconData(0xe872, fontFamily: _kFontFam, fontPackage: null);
  static const IconData search = IconData(0xe873, fontFamily: _kFontFam, fontPackage: null);
  static const IconData unfold_less = IconData(0xe874, fontFamily: _kFontFam, fontPackage: null);
  static const IconData unfold_more = IconData(0xe875, fontFamily: _kFontFam, fontPackage: null);
  static const IconData messenger = IconData(0xe876, fontFamily: _kFontFam, fontPackage: null);
  static const IconData facebook = IconData(0xe877, fontFamily: _kFontFam, fontPackage: null);
  static const IconData instagram = IconData(0xe878, fontFamily: _kFontFam, fontPackage: null);
  static const IconData linkedin = IconData(0xe879, fontFamily: _kFontFam, fontPackage: null);
  static const IconData twitter = IconData(0xe87A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData whatsapp = IconData(0xe87B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData youtube = IconData(0xe87C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData circle_help = IconData(0xe87D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_hand = IconData(0xe87E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData pix = IconData(0xe87F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData accessibility = IconData(0xe889, fontFamily: _kFontFam, fontPackage: null);
  static const IconData location_off = IconData(0xe88A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData phone = IconData(0xe88B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData nubank = IconData(0xe88C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_card_dotted = IconData(0xe88D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_cards = IconData(0xe88E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_card_lock = IconData(0xe88F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_card = IconData(0xe890, fontFamily: _kFontFam, fontPackage: null);
  static const IconData video = IconData(0xe891, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_card_lock_horizontal = IconData(0xe892, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_cards_horizontal = IconData(0xe893, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_card_horizontal = IconData(0xe894, fontFamily: _kFontFam, fontPackage: null);
  static const IconData credit_card_dotted_horizontal = IconData(0xe895, fontFamily: _kFontFam, fontPackage: null);
  static const IconData shopping_bag_outline = IconData(0xe897, fontFamily: _kFontFam, fontPackage: null);
  static const IconData ticket = IconData(0xe898, fontFamily: _kFontFam, fontPackage: null);
  static const IconData up_down = IconData(0xe899, fontFamily: _kFontFam, fontPackage: null);
  static const IconData dollar_sign_bold = IconData(0xe89A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData dollar_sign = IconData(0xe89B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData shopping_bag = IconData(0xe89C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData microphone_small = IconData(0xe8FA, fontFamily: _kFontFam, fontPackage: null);
  static const IconData calendar_important = IconData(0xe90A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData money_refresh = IconData(0xe90B, fontFamily: _kFontFam, fontPackage: null);
  static const IconData email_add = IconData(0xe915, fontFamily: _kFontFam, fontPackage: null);
  static const IconData smartphone_broke = IconData(0xe919, fontFamily: _kFontFam, fontPackage: null);
  static const IconData smartphone_sync = IconData(0xe91A, fontFamily: _kFontFam, fontPackage: null);
  static const IconData wifi = IconData(0xe91C, fontFamily: _kFontFam, fontPackage: null);
  static const IconData lamp = IconData(0xe91D, fontFamily: _kFontFam, fontPackage: null);
  static const IconData drop = IconData(0xe91E, fontFamily: _kFontFam, fontPackage: null);
  static const IconData stop = IconData(0xe91F, fontFamily: _kFontFam, fontPackage: null);
  static const IconData pause = IconData(0xe920, fontFamily: _kFontFam, fontPackage: null);
  static const IconData play = IconData(0xe921, fontFamily: _kFontFam, fontPackage: null);
}
