name: cep_infra
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  hive: ^2.2.1
  connectivity_plus: ^2.3.0
  
  cep_models:
    path: ../cep_models
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.2.0
  build_runner: ^2.1.11
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: