name: home_mobx
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+2

  cep_infra:
    path: ../cep_infra
  cep_models:
    path: ../cep_models
  cep_utils:
    path: ../cep_utils

dev_dependencies:
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
